CREATE DATABASE IF NOT EXISTS UmrahQuoteDB;

USE UmrahQuoteDB;


DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash CHAR(64) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS umrah_quotes;
CREATE TABLE umrah_quotes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quote_accepted boolean NOT NULL,
    consultant_initials VARCHAR(255),
    travel_consultant VARCHAR(255),
    consultant_mobile VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(255),
    package_includes TEXT,
    notes TEXT,
    adults INT,
    youth INT,
    child INT,
    infant INT,
    total_passengers INT,
    airline VARCHAR(255),
    flight_type VARCHAR(255),
    departure_airport VARCHAR(255),
    return_airport VARCHAR(255),
    flight_refund_policy VARCHAR(255),
    departure_date DATE,
    departure_flight_time TEXT,
    return_date DATE,
    return_flight_time TEXT,
    flight_time_upload VARCHAR(255),
    total_nights INT,
    first_destination VARCHAR(255),
    makkah_hotel VARCHAR(255),
    nights_in_makkah INT,
    makkah_hotel_rating INT,
    makkah_check_in_date DATE,
    makkah_check_out_date DATE,
    makkah_room_type VARCHAR(255),
    makkah_board_type VARCHAR(255),
    total_rooms_makkah INT,
    extra_infant_beds_makkah INT,
    total_beds_makkah INT,
    madinah_hotel VARCHAR(255),
    nights_in_madinah INT,
    madinah_hotel_rating INT,
    madinah_check_in_date DATE,
    madinah_check_out_date DATE,
    madinah_room_type VARCHAR(255),
    madinah_board_type VARCHAR(255),
    total_rooms_madinah INT,
    extra_infant_beds_madinah INT,
    total_beds_madinah INT,
    visa VARCHAR(255),
    other_visa VARCHAR(255),
    transport_by_road TEXT,
    transport_by_train TEXT,
    ziaraat TEXT,
    late_check_in VARCHAR(255),
    other_info TEXT,
    flight_rate_adult DECIMAL(10,2),
    flight_rate_youth DECIMAL(10,2),
    flight_rate_child DECIMAL(10,2),
    flight_rate_infant DECIMAL(10,2),
    flight_total DECIMAL(10,2),
    makkah_room_rates DECIMAL(10,2),
    total_makkah_room_cost DECIMAL(10,2),
    total_makkah_room_cost_pp DECIMAL(10,2),
    madinah_room_rates DECIMAL(10,2),
    total_madinah_room_cost DECIMAL(10,2),
    total_madinah_room_cost_pp DECIMAL(10,2),
    average_beds DECIMAL(10,2),
    total_minus_flights_pp DECIMAL(10,2),
    total_hotels_cost DECIMAL(10,2),
    total_hotels_cost_pp DECIMAL(10,2),
    extra_infant_bed_cost DECIMAL(10,2),
    visa_cost_pp DECIMAL(10,2),
    transport_ziaraath_cost_pp DECIMAL(10,2),
    train_cost_pp DECIMAL(10,2),
    total_visa_cost DECIMAL(10,2),
    total_transport_ziaraath_cost DECIMAL(10,2),
    total_train_cost DECIMAL(10,2),
    local_guide_cost DECIMAL(10,2),
    profit_pp DECIMAL(10,2),
    total_profit DECIMAL(10,2),
    adult_price_pp DECIMAL(10,2),
    youth_price_pp DECIMAL(10,2),
    child_price_pp DECIMAL(10,2),
    infant_price_pp DECIMAL(10,2),
    grand_total DECIMAL(10,2),
    total_pp DECIMAL(10,2),
    user_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS quote_versions;
CREATE TABLE quote_versions (
    version_id INT AUTO_INCREMENT PRIMARY KEY,
    quote_id INT,
    version_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (quote_id) REFERENCES umrah_quotes(id)
);
