# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch: # This enables manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest



    strategy:
      matrix:
        node-version: [20.12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
          # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

      # Step 4: Build the app
    - name: Build the app
      run: npm run build
        # Step 5: Deploy build files to FastComet via SFTP
    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.5
      with:
        host: your-fastcomet-host.com
        username: your-cpanel-username
        password: ${{ secrets.FASTCOMET_PASSWORD }} # Set this in GitHub Secrets
        source: build/ # Adjust if necessary
        target: /home4/diamondr/admin.afftravelnet.com/ # Path to your app folder
